version: '3.8'
services:
  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - database  

  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: chefmanager
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/sql:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  pgdata:  
